POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "Kiz",
    "email": "kizito65623281@gmail.com",
    "password": "pending"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "kizito65623281@gmail.com",
    "password": "pendin23"
}

###
POST http://localhost:3000/auth/forget-password
Content-Type: application/json

{
    "email": "kizito65623281@gmail.com"
}

###
POST http://kizito-auth.onrender.com/auth/reset-password/37d4bc75-7e65-4e1f-877c-0a9f49474050
Content-Type: application/json

{
    "newPassword": "pendin23"
}

###
GET   https://kizito-auth.onrender.com/auth/verify-email/aef6913d-9401-4310-9561-f122293021c1